version: '3.7'
services:
  discovery:
    image: 127.0.0.1:5000/secure-journal-discovery:latest
    build: ./discovery
    networks:
      - secure-network    
    ports:
      - "8761:8761"
      - "18787:8787"
    # depends_on:
    #   - config-server
  gateway:
    image: 127.0.0.1:5000/secure-journal-gateway:latest
    build: ./gateway
    ports:
      - "8762:8762"
      - "28787:8787"
    networks:
      - secure-network

  entries:
    image: 127.0.0.1:5000/secure-journal-entries:latest
    build: ./entries
    ports:
      - "8100:8100"
      - "38787:8787"    
    deploy:
      mode: replicated
      replicas: 2      
    networks:
      - secure-network

networks:
    secure-network:
        driver: overlay
        attachable: true




  