spring:
  application:
    name: gateway
server:
  port : 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul: 
  ignoredServices: '*'
  routes:
    auth: 
      path: /auth/**
      serviceId: auth
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    entries:
      path: /entries/**
      serviceId: entries
    analyzer:
      path: /analyzer/**
      serviceId: analyzer

secure-journal.security.jwt.secret: thisIsMyJwTsecRet
secure-journal.security.jwt.url: /auth/**


# Disable the spring security default configuration from spring-boot-actuator
spring.security.enabled: false
management.security.enabled: true
security.basic.enabled: false


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 